insert into public.articles (
  id, date, rank, title, source, url, published_at, read_minutes,
  summary_title, summary, key_points, why_it_matters
)
values
  ('2026-09-17-1', '2026-09-17', 1, $$Markets Steady as Central Banks Hold Rates$$, $$Reuters$$, $$https://www.reuters.com/$$, '2026-09-17T08:10:00.000Z', 4, $$Summary of Article$$,
    jsonb_build_array($$Major central banks kept benchmark rates unchanged, citing cooling inflation and softer labour data.$$, $$Equity indexes opened flat-to-higher as traders priced a longer pause before any cuts.$$, $$Currency markets were quiet, with the dollar little changed against peers.$$),
    jsonb_build_array($$Policy rates held across several G7 economies.$$, $$Inflation progress noted, but services prices remain sticky.$$, $$Investors now watch upcoming jobs and CPI prints.$$),
    $$A prolonged pause shapes mortgage costs, hiring plans, and how companies fund growth.$$),
  ('2026-09-17-2', '2026-09-17', 2, $$New Chip Packaging Push Aims at AI Efficiency$$, $$TechCrunch$$, $$https://techcrunch.com/$$, '2026-09-17T09:40:00.000Z', 5, $$Summary of Article$$,
    jsonb_build_array($$Chipmakers outlined denser packaging techniques meant to move data between dies with less power.$$, $$The approach targets inference workloads that are bottlenecked by memory bandwidth.$$, $$Early partners include cloud providers testing the stacks in production clusters.$$),
    jsonb_build_array($$Focus is packaging, not a new transistor node.$$, $$Goal: more tokens per watt for AI serving.$$, $$Cloud pilots expected before wider OEM adoption.$$),
    $$Lower inference cost could widen who can run capable models at scale.$$),
  ('2026-09-17-3', '2026-09-17', 3, $$Heatwave Tests Power Grids Across Southern Europe$$, $$BBC World$$, $$https://www.bbc.com/news$$, '2026-09-17T07:05:00.000Z', 3, $$Summary of Article$$,
    jsonb_build_array($$Record afternoon temperatures drove air-conditioning demand to seasonal highs.$$, $$Grid operators issued conservation notices and delayed non-critical maintenance.$$, $$Hospitals and transit agencies activated heat contingency plans.$$),
    jsonb_build_array($$Peak load arrived earlier than usual this week.$$, $$Conservation notices cover several metro areas.$$, $$Health services are monitoring vulnerable groups.$$),
    $$Repeated peak-load days expose how climate stress hits everyday infrastructure.$$),
  ('2026-09-17-4', '2026-09-17', 4, $$Cities Expand Congestion Pricing After Pilot Gains$$, $$Associated Press$$, $$https://apnews.com/$$, '2026-09-17T11:20:00.000Z', 4, $$Summary of Article$$,
    jsonb_build_array($$Two more metro regions approved downtown tolls after pilots cut peak traffic.$$, $$Revenue is earmarked for buses and protected bike lanes.$$, $$Business groups remain split on exemptions for deliveries.$$),
    jsonb_build_array($$Pilots showed faster bus times in core corridors.$$, $$New funds go to transit, not general budgets.$$, $$Delivery exemptions are still under debate.$$),
    null),
  ('2026-09-17-5', '2026-09-17', 5, $$Open-Source Model Beats Closed Rival on Coding Bench$$, $$Hacker News$$, $$https://news.ycombinator.com/$$, '2026-09-17T13:00:00.000Z', 3, $$Summary of Article$$,
    jsonb_build_array($$A newly released open weights model topped a popular software-engineering benchmark.$$, $$Researchers credited stronger tool-use training and longer context windows.$$, $$Enterprises are testing local deployment for code assistants.$$),
    jsonb_build_array($$Open weights matched or beat a leading closed model.$$, $$Tool-use training was a major lever.$$, $$Local deploy interest is rising for privacy.$$),
    null),
  ('2026-09-17-6', '2026-09-17', 6, $$Vaccine Update Clears Review for Fall Campaign$$, $$NPR$$, $$https://www.npr.org/$$, '2026-09-17T06:30:00.000Z', 3, $$Summary of Article$$,
    jsonb_build_array($$Regulators cleared an updated formulation matched to circulating strains.$$, $$Public clinics will open appointments ahead of the colder months.$$, $$Officials urged higher-risk groups to book early.$$),
    jsonb_build_array($$Updated strain match approved.$$, $$Clinic appointments open this month.$$, $$Priority messaging targets higher-risk groups.$$),
    null),
  ('2026-09-17-7', '2026-09-17', 7, $$Streaming Services Bundle Sports to Slow Churn$$, $$The Verge$$, $$https://www.theverge.com/$$, '2026-09-17T14:15:00.000Z', 4, $$Summary of Article$$,
    jsonb_build_array($$Two major streamers announced a joint sports tier after subscriber growth cooled.$$, $$The package mixes live events with on-demand highlights.$$, $$Analysts say the move is about retention more than new sign-ups.$$),
    jsonb_build_array($$Joint sports tier aims at retention.$$, $$Live rights are the expensive piece.$$, $$Churn, not acquisition, is the near-term KPI.$$),
    null),
  ('2026-09-17-8', '2026-09-17', 8, $$Trade Talks Restart With Narrower Agenda$$, $$The Guardian$$, $$https://www.theguardian.com/$$, '2026-09-17T10:00:00.000Z', 5, $$Summary of Article$$,
    jsonb_build_array($$Negotiators reconvened after months of stalled discussions.$$, $$The new agenda focuses on industrial goods and digital services, leaving agriculture aside.$$, $$Officials set a 90-day window for a draft framework.$$),
    jsonb_build_array($$Talks resume with a narrower scope.$$, $$Agriculture is parked for now.$$, $$Draft framework targeted in 90 days.$$),
    null),
  ('2026-09-17-9', '2026-09-17', 9, $$Battery Recycling Plant Opens Near Port Corridor$$, $$Wired$$, $$https://www.wired.com/$$, '2026-09-17T12:45:00.000Z', 4, $$Summary of Article$$,
    jsonb_build_array($$A new facility will recover lithium, nickel, and cobalt from end-of-life EV packs.$$, $$Operators say closed-loop supply can cut mining demand for regional manufacturers.$$, $$Local officials tied the project to port-adjacent job growth.$$),
    jsonb_build_array($$Focus on EV pack materials recovery.$$, $$Aims to feed nearby cell plants.$$, $$Jobs pitch tied to port logistics.$$),
    null),
  ('2026-09-17-10', '2026-09-17', 10, $$Schools Trial Phone-Free Mornings After Focus Study$$, $$Al Jazeera$$, $$https://www.aljazeera.com/$$, '2026-09-17T15:20:00.000Z', 3, $$Summary of Article$$,
    jsonb_build_array($$A district pilot locks phones away until lunch after a study linked morning use to weaker attention.$$, $$Teachers reported fewer interruptions in the first two weeks.$$, $$Parents are split on emergency access rules.$$),
    jsonb_build_array($$Morning phone lockup in pilot schools.$$, $$Early reports of fewer classroom interruptions.$$, $$Emergency access policy still contested.$$),
    null),
  ('2026-09-16-1', '2026-09-16', 1, $$Satellite Internet Expands to Remote Clinics$$, $$NPR$$, $$https://www.npr.org/$$, '2026-09-16T09:00:00.000Z', 4, $$Summary of Article$$,
    jsonb_build_array($$A health network connected dozens of rural clinics to low-latency satellite links.$$, $$Doctors can now run tele-specialty consults without driving patients hours away.$$, $$Uptime during storms remains the main open question.$$),
    jsonb_build_array($$Rural clinics gain satellite broadband.$$, $$Tele-specialty consults become practical.$$, $$Weather resilience still being measured.$$),
    null),
  ('2026-09-16-2', '2026-09-16', 2, $$Automakers Align on Shared Charging Standard$$, $$Reuters$$, $$https://www.reuters.com/$$, '2026-09-16T08:20:00.000Z', 3, $$Summary of Article$$,
    jsonb_build_array($$Several manufacturers agreed to support one plug standard at new highway chargers.$$, $$Adapters will cover older vehicles during a multi-year transition.$$, $$Drivers should see fewer dead-end station visits.$$),
    jsonb_build_array($$Shared plug standard for new stations.$$, $$Adapters bridge older cars.$$, $$Goal is less charging confusion on highways.$$),
    null),
  ('2026-09-16-3', '2026-09-16', 3, $$Cybersecurity Bill Adds Breach Deadline Rules$$, $$Associated Press$$, $$https://apnews.com/$$, '2026-09-16T11:10:00.000Z', 4, $$Summary of Article$$,
    jsonb_build_array($$Lawmakers advanced rules requiring faster public disclosure after major breaches.$$, $$Companies must notify regulators within a fixed window once an incident is confirmed.$$, $$Small firms get a longer runway and template guidance.$$),
    jsonb_build_array($$Faster breach disclosure mandates.$$, $$Fixed notification windows for regulators.$$, $$Smaller firms get extra compliance time.$$),
    null),
  ('2026-09-16-4', '2026-09-16', 4, $$Indie Game Studio Sale Sparks Talent Concerns$$, $$The Verge$$, $$https://www.theverge.com/$$, '2026-09-16T16:00:00.000Z', 3, $$Summary of Article$$,
    jsonb_build_array($$A beloved studio was acquired by a larger publisher after a breakout release.$$, $$Staff asked for written guarantees on creative control and remote work.$$, $$Fans worry sequels will chase live-service metrics.$$),
    jsonb_build_array($$Breakout studio acquired by a big publisher.$$, $$Staff seeking creative-control guarantees.$$, $$Community nervous about sequel direction.$$),
    null),
  ('2026-09-16-5', '2026-09-16', 5, $$Drought Forces Shipping Draft Limits on Key River$$, $$BBC World$$, $$https://www.bbc.com/news$$, '2026-09-16T07:40:00.000Z', 4, $$Summary of Article$$,
    jsonb_build_array($$Low water levels prompted temporary draft limits for barges on a major trade river.$$, $$Grain and fuel shipments are being split across more vessels.$$, $$Analysts expect higher inland freight costs this month.$$),
    jsonb_build_array($$Low river levels trigger draft limits.$$, $$Cargoes split across more barges.$$, $$Inland freight costs likely to rise.$$),
    null),
  ('2026-09-16-6', '2026-09-16', 6, $$Browser Vendors Tighten Default Tracking Shields$$, $$Wired$$, $$https://www.wired.com/$$, '2026-09-16T13:30:00.000Z', 3, $$Summary of Article$$,
    jsonb_build_array($$Default cookie and fingerprinting protections will expand in upcoming browser releases.$$, $$Ad networks are testing contextual alternatives.$$, $$Publishers warn of short-term revenue dips.$$),
    jsonb_build_array($$Stronger default anti-tracking in browsers.$$, $$Ads shifting toward contextual targeting.$$, $$Publishers brace for revenue pressure.$$),
    null),
  ('2026-09-16-7', '2026-09-16', 7, $$University Opens Shared Lab for Climate Sensors$$, $$The Guardian$$, $$https://www.theguardian.com/$$, '2026-09-16T10:50:00.000Z', 3, $$Summary of Article$$,
    jsonb_build_array($$A new shared lab will let startups and city agencies prototype low-cost climate sensors.$$, $$First projects focus on urban heat and flood early warning.$$, $$Data will be published under an open license.$$),
    jsonb_build_array($$Shared climate-sensor lab opens.$$, $$Early focus: heat and flood alerts.$$, $$Open data license for outputs.$$),
    null),
  ('2026-09-16-8', '2026-09-16', 8, $$Rail Strike Averted After Overnight Mediation$$, $$Al Jazeera$$, $$https://www.aljazeera.com/$$, '2026-09-16T05:15:00.000Z', 2, $$Summary of Article$$,
    jsonb_build_array($$Unions and operators reached a tentative deal hours before a planned walkout.$$, $$The agreement covers pay, rest schedules, and safety staffing.$$, $$Members still need to ratify the deal.$$),
    jsonb_build_array($$Walkout paused after overnight talks.$$, $$Deal covers pay and rest schedules.$$, $$Ratification vote still pending.$$),
    null),
  ('2026-09-16-9', '2026-09-16', 9, $$Startup Ships Pocket Ultrasound for Field Clinics$$, $$TechCrunch$$, $$https://techcrunch.com/$$, '2026-09-16T15:45:00.000Z', 4, $$Summary of Article$$,
    jsonb_build_array($$A handheld ultrasound device began shipping to field clinics after regulatory clearance.$$, $$Images sync to a phone app with guided capture for less-trained operators.$$, $$Pricing targets NGOs and community hospitals.$$),
    jsonb_build_array($$Pocket ultrasound now shipping.$$, $$Phone app guides less-trained users.$$, $$NGO and community hospital pricing.$$),
    null),
  ('2026-09-16-10', '2026-09-16', 10, $$Museum Returns Artefacts After Provenance Review$$, $$Hacker News$$, $$https://news.ycombinator.com/$$, '2026-09-16T18:00:00.000Z', 3, $$Summary of Article$$,
    jsonb_build_array($$A major museum completed a provenance review and returned several contested artefacts.$$, $$The process included historians from the artefacts' countries of origin.$$, $$Other institutions said they will publish similar review timelines.$$),
    jsonb_build_array($$Provenance review leads to returns.$$, $$Origin-country historians joined the process.$$, $$Peer museums signaling similar reviews.$$),
    null)
on conflict (id) do update set
  date = excluded.date,
  rank = excluded.rank,
  title = excluded.title,
  source = excluded.source,
  url = excluded.url,
  published_at = excluded.published_at,
  read_minutes = excluded.read_minutes,
  summary_title = excluded.summary_title,
  summary = excluded.summary,
  key_points = excluded.key_points,
  why_it_matters = excluded.why_it_matters;
